package com.sa.java.modules.sys.entity;

import com.sa.java.modules.sys.entity.base.BaseRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Right extends BaseRight<Right> {
	public static final Right dao = new Right();
}
