package com.sa.java.modules.sys.entity;

import com.sa.java.modules.sys.entity.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
}
