package com.sa.java.modules.sys.entity;

import com.sa.java.modules.sys.entity.base.BaseRoleRight;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleRight extends BaseRoleRight<RoleRight> {
	public static final RoleRight dao = new RoleRight();
}
