package com.sa.java.modules.sys.entity;

import com.sa.java.modules.sys.entity.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
}
