package com.sa.java.modules.sys.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleRight<M extends BaseRoleRight<M>> extends Model<M> implements IBean {

	public void setRoleId(java.lang.Integer roleId) {
		set("role_id", roleId);
	}

	public java.lang.Integer getRoleId() {
		return get("role_id");
	}

	public void setRightId(java.lang.Integer rightId) {
		set("right_id", rightId);
	}

	public java.lang.Integer getRightId() {
		return get("right_id");
	}

}
